"""
Language resources for the emotion analyzer: emotion lexicon, negation and
intensifier words, emoji map, greetings and language names.

Pure data, no logic. To teach the analyzer a new word, add it to the right
``LEXICON[emotion][language]`` list; to support a new language, add the
language code to the lexicon (and optionally to ``STOPWORDS`` so it can be
detected from Latin script). ``EmotionDetection.engine`` compiles everything
into lookup tables at import time, so no other change is needed.
"""

from __future__ import annotations

from typing import Dict, List

# Words that flip the meaning of whatever emotion word follows within a
# short window (e.g. "not happy", "δεν χαίρομαι", "no estoy feliz").
# Extend this per-language as needed; languages without an entry simply
# skip negation handling rather than guessing.
NEGATIONS: Dict[str, set] = {
    "en": {"not", "no", "never", "n't", "cannot", "dont", "don't", "wont",
           "won't", "isnt", "isn't", "wasnt", "wasn't", "cant", "can't",
           "didnt", "didn't", "doesnt", "doesn't", "hardly", "barely"},
    "el": {"δεν", "όχι", "ποτέ", "μη", "μην", "καθόλου"},
    "es": {"no", "nunca", "jamás", "tampoco", "ni"},
    "pt": {"não", "nunca", "jamais", "nem"},
    "fr": {"ne", "pas", "jamais", "non", "aucun"},
    "de": {"nicht", "kein", "keine", "niemals", "nie"},
    "it": {"non", "mai", "nessuno"},
}

# Words that amplify the strength of whatever emotion word follows.
INTENSIFIERS: Dict[str, set] = {
    "en": {"very", "extremely", "really", "so", "totally", "absolutely",
           "incredibly", "super", "utterly", "completely"},
    "el": {"πολύ", "πάρα", "εξαιρετικά", "απίστευτα", "τρομερά"},
    "es": {"muy", "super", "extremadamente", "totalmente", "increíblemente"},
    "pt": {"muito", "super", "extremamente", "totalmente"},
    "fr": {"très", "extrêmement", "totalement", "vraiment"},
    "de": {"sehr", "äußerst", "total", "wirklich"},
    "it": {"molto", "estremamente", "totalmente", "davvero"},
}

# Unambiguous emoji → emotion signal. Scanned on the raw text (before
# punctuation stripping) since emoji are non-word characters.
EMOJI_EMOTIONS: Dict[str, str] = {
    "😀": "joy", "😃": "joy", "😄": "joy", "😁": "joy", "😊": "joy",
    "🙂": "joy", "😍": "joy", "🥰": "joy", "🥳": "joy", "❤️": "joy",
    "💕": "joy", "🎉": "joy", "👍": "joy", "😂": "joy", "🤣": "joy",
    "😢": "sadness", "😭": "sadness", "😔": "sadness", "☹️": "sadness",
    "😞": "sadness", "💔": "sadness", "😥": "sadness", "🙁": "sadness",
    "😡": "anger", "😠": "anger", "🤬": "anger", "👿": "anger", "😤": "anger",
    "😨": "fear", "😱": "fear", "😰": "fear", "😟": "fear", "😧": "fear",
    "🤢": "disgust", "🤮": "disgust", "😖": "disgust", "🤧": "disgust",
    "😲": "surprise", "😮": "surprise", "😳": "surprise", "🤯": "surprise",
    "😯": "surprise",
}


# Multilingual emotion lexicon.
# Compact, hand-curated words for 50+ of the world's most spoken languages.
LEXICON: Dict[str, Dict[str, List[str]]] = {
    "joy": {
        "en": ["happy", "happiness", "joy", "joyful", "glad", "delighted",
               "love", "loved", "amazing", "awesome", "great", "good", "wonderful",
               "fantastic", "thrilled", "excited", "smile", "laughing", "lol",
               "yay", "yes", "perfect", "best", "beautiful", "thanks", "thank",
               "promoted", "promotion", "promote", "raise", "bonus", "hired",
               "achievement", "achieved", "achieve", "success", "successful",
               "proud", "congrats", "congratulations", "celebrate", "celebrating",
               "win", "won", "winning", "excellent", "incredible", "blessed",
               "graduated", "graduation", "engaged", "married"],
        "es": ["feliz", "alegre", "alegría", "amor", "amo", "genial", "increíble",
               "maravilloso", "fantástico", "gracias", "sonrisa", "sí"],
        "pt": ["feliz", "alegria", "amor", "amo", "ótimo", "incrível", "obrigado",
               "obrigada", "sorriso", "sim"],
        "fr": ["heureux", "heureuse", "joie", "amour", "j'aime", "génial",
               "incroyable", "merci", "sourire", "oui"],
        "de": ["glücklich", "freude", "liebe", "ich liebe", "super", "toll",
               "wunderbar", "danke", "lächeln", "ja"],
        "it": ["felice", "gioia", "amore", "amo", "fantastico", "grazie", "sorriso", "sì"],
        "nl": ["blij", "gelukkig", "liefde", "hou van", "geweldig", "dank", "glimlach"],
        "el": ["χαρούμενος", "χαρούμενη", "χαρά", "αγάπη", "αγαπώ", "τέλεια", "ευχαριστώ"],
        "ru": ["счастлив", "счастье", "радость", "люблю", "любовь", "отлично",
               "спасибо", "улыбка", "да"],
        "uk": ["щасливий", "радість", "люблю", "кохання", "супер", "дякую"],
        "pl": ["szczęśliwy", "radość", "miłość", "kocham", "super", "dziękuję", "uśmiech"],
        "cs": ["šťastný", "radost", "láska", "miluji", "skvělé", "díky"],
        "tr": ["mutlu", "sevinç", "aşk", "seviyorum", "harika", "teşekkürler", "gülümseme"],
        "ar": ["سعيد", "سعادة", "فرح", "حب", "أحبك", "رائع", "شكرا", "ابتسامة"],
        "he": ["שמח", "שמחה", "אושר", "אהבה", "אוהב", "תודה", "נהדר"],
        "fa": ["خوشحال", "شادی", "عشق", "دوستت دارم", "عالی", "ممنون"],
        "hi": ["खुश", "खुशी", "प्रेम", "प्यार", "शानदार", "धन्यवाद", "मुस्कान"],
        "bn": ["আনন্দ", "ভালোবাসা", "ভালোবাসি", "দারুণ", "ধন্যবাদ"],
        "ta": ["மகிழ்ச்சி", "அன்பு", "நான் அன்பு", "நன்றி", "சூப்பர்"],
        "te": ["సంతోషం", "ప్రేమ", "ధన్యవాదాలు"],
        "th": ["มีความสุข", "สุข", "รัก", "ขอบคุณ", "ยิ้ม"],
        "vi": ["vui", "hạnh phúc", "yêu", "tuyệt vời", "cảm ơn", "cười"],
        "id": ["senang", "bahagia", "cinta", "sayang", "terima kasih", "hebat"],
        "ms": ["gembira", "cinta", "sayang", "terima kasih", "hebat"],
        "tl": ["masaya", "ligaya", "mahal", "salamat"],
        "ja": ["嬉しい", "幸せ", "喜び", "愛", "愛してる", "素晴らしい", "ありがとう", "笑顔"],
        "ko": ["기쁘다", "행복", "기쁨", "사랑", "사랑해", "최고", "고마워", "미소"],
        "zh": ["开心", "高兴", "快乐", "幸福", "爱", "我爱你", "太好了", "谢谢", "微笑"],
        "yue": ["開心", "快樂", "愛", "多謝"],
        "sw": ["furaha", "penzi", "napenda", "asante"],
        "af": ["gelukkig", "liefde", "dankie"],
        "fi": ["onnellinen", "ilo", "rakkaus", "rakastan", "kiitos"],
        "sv": ["glad", "lycka", "kärlek", "älskar", "tack", "leende"],
        "no": ["glad", "lykke", "kjærlighet", "elsker", "takk"],
        "da": ["glad", "lykke", "kærlighed", "elsker", "tak"],
        "ro": ["fericit", "bucurie", "iubire", "iubesc", "mulțumesc", "zâmbet"],
        "hu": ["boldog", "öröm", "szeretet", "szeretem", "köszönöm"],
        "bg": ["щастлив", "щастие", "любов", "обичам", "благодаря", "усмивка"],
        "sr": ["срећан", "срећа", "љубав", "волим", "хвала"],
        "hr": ["sretan", "sreća", "ljubav", "volim", "hvala"],
        "sk": ["šťastný", "radosť", "láska", "ľúbim", "ďakujem"],
        "lt": ["laimingas", "džiaugsmas", "meilė", "aš tave myliu", "ačiū"],
        "lv": ["laimīgs", "prieks", "mīlestība", "mīlu", "paldies"],
        "sl": ["srečen", "sreča", "ljubezen", "ljubim", "hvala"],
        "et": ["õnnelik", "rõõm", "armastus", "armastan", "aitäh"],
        "ca": ["feliç", "alegria", "amor", "estim", "gràcies", "somriure"],
        "gl": ["feliz", "ledicia", "amor", "amo", "grazas"],
        "eu": ["zoriontsu", "alaitasun", "maitasun", "maite zaitut", "eskerrik asko"],
        "cy": ["hapus", "llawenydd", "cariad", "caru", "diolch"],
        "ga": ["sona", "sonas", "grá", "grámhar", "go raibh maith agat"],
        "mt": ["ferħan", "ferħ", "imħabba", "grazzi"],
        "is": ["hamingjusamur", "gleði", "ást", "elska", "takk"],
        "eo": ["feliĉa", "ĝojo", "amo", "dankon"],
        "la": ["laetus", "gaudium", "amor", "amo", "gratias"],
    },
    "sadness": {
        "en": ["sad", "sadness", "cry", "crying", "tears", "miss", "missing",
               "lonely", "alone", "lost", "broken", "heartbroken", "depressed",
               "unhappy", "sorrow", "grief", "hurt", "pain", "regret", "ex",
               "goodbye", "good bye", "good-bye", "farewell"],
        "es": ["triste", "tristeza", "llorar", "llanto", "solo", "sola",
               "corazón roto", "adiós", "te extraño", "extraño"],
        "pt": ["triste", "tristeza", "chorar", "choro", "sozinho", "sozinha",
               "coração partido", "adeus", "saudade", "sinto sua falta"],
        "fr": ["triste", "tristesse", "pleurer", "seul", "seule", "cœur brisé",
               "au revoir", "tu me manques", "manque"],
        "de": ["traurig", "traurigkeit", "weinen", "einsam", "gebrochen",
               "herz gebrochen", "tschuess", "vermissen", "fehlen"],
        "it": ["triste", "tristezza", "piangere", "solo", "sola", "cuore spezzato",
               "addio", "mi manchi", "manca"],
        "nl": ["verdrietig", "verdriet", "huilen", "alleen", "gebroken", "vermissen"],
        "el": ["λυπημένος", "λύπη", "κλαίω", "μόνος", "μόνη", "σπασμένη καρδιά",
               "μου λείπεις", "μου λείπει", "αντίο"],
        "ru": ["грустный", "грусть", "плакать", "одинокий", "разбитое сердце",
               "скучаю", "прощай", "не хватает"],
        "uk": ["сумний", "сум", "плакати", "самотній", "сумую"],
        "pl": ["smutny", "smutek", "płakać", "samotny", "serce złamane", "tęsknię"],
        "cs": ["smutný", "smutek", "plakat", "osamělý", "zlomené srdce", "chybíš mi"],
        "tr": ["üzgün", "hüzün", "ağlamak", "yalnız", "kırık", "özledim"],
        "ar": ["حزين", "حزن", "أبكي", "وحيد", "قلب مكسور", "أشتاق"],
        "he": ["עצוב", "עצב", "בוכה", "בודד", "לב שבור", "אני מתגעגע"],
        "fa": ["غمگین", "غصه", "گریه", "تنها", "دلم تنگ شده"],
        "hi": ["उदास", "दुख", "रोना", "अकेला", "टूटा दिल", "याद"],
        "bn": ["দুঃখ", "কাঁদা", "একা", "ভাঙা হৃদয়"],
        "th": ["เศร้า", "ร้องไห้", "เหงา", "คิดถึง"],
        "vi": ["buồn", "khóc", "cô đơn", "nhớ", "nhớ bạn"],
        "id": ["sedih", "menangis", "kesepian", "rindu"],
        "ja": ["悲しい", "悲しみ", "泣く", "寂しい", "失恋", "さようなら", "会いたい"],
        "ko": ["슬프다", "슬픔", "울다", "외롭다", "이별", "그리워"],
        "zh": ["伤心", "难过", "悲伤", "哭", "孤独", "想念", "失恋", "再见"],
        "yue": ["傷心", "喊", "掛住"],
        "sw": ["huzuni", "kulia", "upweke", "nakukumbuka"],
        "af": ["hartseer", "huil", "eensaam"],
        "fi": ["surullinen", "itkeä", "yksinäinen", "ikävä"],
        "sv": ["ledsen", "sorg", "gråta", "ensam", "saknar dig"],
        "no": ["trist", "gråte", "ensom", "savner deg"],
        "da": ["trist", "græde", "ensom", "savner dig"],
        "ro": ["trist", "plâng", "singur", "mi-e dor de tine"],
        "hu": ["szomorú", "sír", "egyedül", "hiányzol"],
        "bg": ["тъжен", "плача", "самотен", "липсваш ми"],
        "sr": ["тужан", "плачем", "усамљен", "недостајеш ми"],
        "hr": ["tužan", "plačem", "usamljen", "nedostaješ mi"],
        "sk": ["smutný", "plačem", "osamelý", "chýbaš mi"],
        "lt": ["liūdnas", "verkiu", "vienišas", "pasilieku tavęs"],
        "lv": ["skumjš", "raudu", "vientuļš", "tevis pietrūkst"],
        "sl": ["žalosten", "jokam", "osamljen", "pogrešam te"],
        "et": ["kurb", "nutma", "üksildane", "igatsen sind"],
        "ca": ["trist", "plor", "sol", "trobar a faltar"],
        "gl": ["triste", "chorar", "só", "botar de menos"],
        "eu": ["triste", "negar", "bakartia", "falta zait"],
        "cy": ["trist", "crio", "unig", "wedi colli"],
        "ga": ["brónach", "ag caoineadh", "aonraic", "imíonn tú uaim"],
        "mt": ["imnikket", "nibki", "waħdi", "nieqes"],
        "is": ["sorgmæddur", "grátur", "einn", "sakna þín"],
        "eo": ["malĝoja", "ploras", "sola", "mankas vi"],
        "la": ["tristis", "fleo", "solus", "desidero te"],
    },
    "anger": {
        "en": ["angry", "anger", "mad", "furious", "rage", "hate", "hated",
               "annoyed", "irritated", "frustrated", "frustration", "pissed",
               "wtf", "damn", "stupid", "idiot", "shut up"],
        "es": ["enojado", "enfadado", "rabia", "furia", "odio", "estúpido"],
        "pt": ["irritado", "raiva", "fúria", "ódio", "idiota", "estúpido"],
        "fr": ["en colère", "fâché", "rage", "colère", "haine", "idiot"],
        "de": ["wütend", "zornig", "wut", "hass", "idiot"],
        "it": ["arrabbiato", "rabbia", "furia", "odio", "stupido", "idiota"],
        "nl": ["boos", "kwaad", "woede", "haat", "idiot", "dom"],
        "el": ["θυμωμένος", "θυμός", "οργή", "μίσος", "ηλίθιος", "βλάκας"],
        "ru": ["злой", "гнев", "ярость", "ненависть", "идиот", "тупой"],
        "uk": ["сердитий", "гнів", "лють", "ненависть"],
        "pl": ["zły", "gniew", "wściekłość", "nienawiść", "idiota"],
        "tr": ["kızgın", "öfke", "nefret", "aptal"],
        "ar": ["غاضب", "غضب", "كراهية", "أحمق"],
        "he": ["כועס", "זעם", "שנאה", "טיפש"],
        "hi": ["गुस्सा", "क्रोध", "घृणा", "मूर्ख"],
        "ja": ["怒り", "激怒", "嫌い", "バカ", "くそ"],
        "ko": ["화난", "분노", "증오", "바보", "씨발"],
        "zh": ["生气", "愤怒", "恨", "讨厌", "傻", "操"],
        "th": ["โกรธ", "โกรธจัด", "เกลียด", "โง่"],
        "vi": ["giận", "tức giận", "ghét", "ngu"],
        "id": ["marah", "kemarahan", "benci", "bodoh"],
        "sw": ["hasira", "chuki", "mpumbavu"],
        "af": ["kwaad", "woede", "haat", "dom"],
        "fi": ["vihainen", "viha", "vihaa", "tyhmä"],
        "sv": ["arg", "ilska", "hat", "dum"],
        "no": ["sint", "sinne", "hat", "dum"],
        "da": ["vred", "vrede", "had", "dum"],
        "ro": ["furios", "furie", "ură", "idiot"],
        "hu": ["dühös", "düh", "gyűlölet", "idióta"],
        "bg": ["ядосан", "гняв", "омраза", "идиот"],
        "sr": ["ljut", "bes", "mržnja", "idiot"],
        "hr": ["ljut", "bijes", "mržnja", "idiot"],
        "sk": ["nahnevaný", "hnev", "nenávisť", "idiot"],
        "lt": ["piktas", "pyktis", "neapykanta", "kvailys"],
        "lv": ["dusmīgs", "dusmas", "naids", "idiot"],
        "sl": ["jezen", "jeza", "sovraštvo", "idiot"],
        "et": ["vihane", "viha", "vihkamine", "idiot"],
        "eo": ["kolera", "kolero", "malamo", "stultulo"],
        "la": ["iratus", "ira", "odium", "stultus"],
    },
    "fear": {
        "en": ["afraid", "scared", "fear", "frightened", "terrified", "panic",
               "anxious", "anxiety", "worried", "worry", "nervous", "stress",
               "stressed", "help", "danger", "unsafe"],
        "es": ["asustado", "miedo", "temor", "aterrorizado", "ansioso",
               "preocupado", "nervioso", "peligro"],
        "pt": ["assustado", "medo", "aterrorizado", "ansioso", "preocupado", "perigo"],
        "fr": ["effrayé", "peur", "terrifié", "anxieux", "inquiet", "danger"],
        "de": ["ängstlich", "angst", "verängstigt", "besorgt", "gefahr"],
        "it": ["spaventato", "paura", "terrorizzato", "ansioso", "preoccupato", "pericolo"],
        "nl": ["bang", "angst", "bang gemaakt", "bezorgd", "gevaar"],
        "el": ["φοβισμένος", "φόβος", "τρομαγμένος", "άγχος", "ανήσυχος", "κίνδυνος"],
        "ru": ["испуганный", "страх", "боюсь", "тревожный", "опасность"],
        "tr": ["korkmuş", "korku", "tedirgin", "tehlike"],
        "ar": ["خائف", "خوف", "قلق", "خطر"],
        "he": ["מפחד", "פחד", "חרדה", "סכנה"],
        "ja": ["怖い", "恐怖", "不安", "心配", "危険"],
        "ko": ["무서운", "두려움", "불안", "걱정", "위험"],
        "zh": ["害怕", "恐惧", "担心", "焦虑", "危险"],
        "th": ["กลัว", "ความกลัว", "วิตกกังวล", "อันตราย"],
        "vi": ["sợ", "sợ hãi", "lo lắng", "nguy hiểm"],
        "id": ["takut", "ketakutan", "cemas", "bahaya"],
        "af": ["bang", "vrees", "bekommerd", "gevaar"],
        "fi": ["pelokas", "pelko", "ahdistunut", "vaara"],
        "sv": ["rädd", "rädsla", "orolig", "fara"],
        "no": ["redd", "frykt", "engstelig", "fare"],
        "da": ["bange", "frygt", "urolig", "fare"],
        "ro": ["speriat", "frică", "anxios", "pericol"],
        "hu": ["fél", "félelem", "szorong", "veszély"],
        "bg": ["уплашен", "страх", "тревожен", "опасност"],
        "sr": ["uplašen", "strah", "uznemiren", "opasnost"],
        "hr": ["uplašen", "strah", "uznemiren", "opasnost"],
        "sk": ["vystrašený", "strach", "znepokojený", "nebezpečenstvo"],
        "lt": ["išsigandęs", "baimė", "nerimas", "pavojus"],
        "lv": ["bailīgs", "bailes", "noraizējies", "briesmas"],
        "sl": ["prestrašen", "strah", "zaskrbljen", "nevarnost"],
        "et": ["hirmunud", "hirm", "mures", "oht"],
        "eo": ["timigita", "timo", "zorgema", "danĝero"],
        "la": ["timidus", "timor", "anxius", "periculum"],
    },
    "disgust": {
        "en": ["disgust", "disgusted", "gross", "nasty", "sick", "sick of",
               "revolting", "repulsive", "yuck", "ew", "eww", "horrible", "terrible",
               "bad", "worst", "awful", "sucks", "sucked"],
        "es": ["asco", "asqueroso", "repugnante", "horrible", "terrible"],
        "pt": ["nojo", "nojento", "repugnante", "horrível", "terrível"],
        "fr": ["dégoût", "dégoûtant", "répugnant", "horrible", "terrible"],
        "de": ["ekel", "ekelhaft", "widerlich", "scheußlich", "furchtbar"],
        "it": ["disgusto", "disgustato", "ripugnante", "orribile", "terribile"],
        "nl": ["walging", "walgelijk", "weerzinwekkend", "vreselijk"],
        "el": ["αηδία", "αηδιασμένος", "αποκρουστικός", "απαίσιος"],
        "ru": ["отвращение", "отвратительный", "омерзительный", "ужасный"],
        "tr": ["iğrenç", "tiksinmek", "mide bulantısı", "berbat"],
        "ar": ["اشمئزاز", "مقرف", "فظيع", "سيء"],
        "he": ["גועל", "מגעיל", "נורא"],
        "ja": ["嫌悪", "気持ち悪い", "不快", "ひどい"],
        "ko": ["혐오", "구역질", "끔찍한", "싫다"],
        "zh": ["恶心", "厌恶", "讨厌", "糟糕"],
        "th": ["รังเกียจ", "น่าขยะแขยง", "แย่"],
        "vi": ["ghê tởm", "kinh tởm", "tồi tệ"],
        "id": ["muak", "menjijikkan", "buruk"],
        "af": ["walg", "walglike", "vreselik"],
        "fi": ["inhottava", "iljettävä", "kauhea"],
        "sv": ["äckligt", "avsky", "hemskt"],
        "no": ["ekkelt", "avsky", "forferdelig"],
        "da": ["ulækkert", "afsky", "forfærdeligt"],
        "ro": ["dezgust", "dezgustător", "groaznic"],
        "hu": ["undor", "undorító", "szörnyű"],
        "bg": ["отвращение", "отвратително", "ужасно"],
        "sr": ["gađenje", "gadno", "užasno"],
        "hr": ["gađenje", "gadno", "užasno"],
        "sk": ["hnus", "hnusný", "hrozné"],
        "lt": ["pasibjaurėjimas", "bjaurus", "baisu"],
        "lv": ["riebums", "riebīgs", "briesmīgi"],
        "sl": ["gnus", "grozen", "grozljivo"],
        "et": ["jälestus", "jälk", "kohutav"],
        "eo": ["naŭzo", "naŭza", "terura"],
        "la": ["fastidium", "foedus", "terribilis"],
    },
    "surprise": {
        "en": ["surprised", "surprise", "wow", "omg", "shock", "shocked",
               "unbelievable", "no way", "cant believe"],
        "es": ["sorpresa", "sorprendido", "increíble", "guau"],
        "pt": ["surpresa", "surpreso", "incrível", "uau"],
        "fr": ["surprise", "surpris", "incroyable", "waouh"],
        "de": ["überrascht", "überraschung", "unglaublich", "wow"],
        "it": ["sorpresa", "sorpreso", "incredibile", "wow"],
        "nl": ["verrast", "verrassing", "ongelooflijk", "wauw"],
        "el": ["έκπληξη", "έκπληκτος", "απίστευτο", "ουάου"],
        "ru": ["удивлён", "удивление", "невероятно", "ого"],
        "tr": ["şaşkın", "şaşırtıcı", "inanılmaz", "vay"],
        "ar": ["مندهش", "مفاجأة", "لا يصدق", "واو"],
        "he": ["מופתע", "הפתעה", "בלתי יאומן"],
        "ja": ["驚き", "驚いた", "すごい", "えっ"],
        "ko": ["놀란", "놀라움", "대단하다", "헐"],
        "zh": ["惊讶", "惊喜", "难以置信", "哇"],
        "th": ["ประหลาดใจ", "เซอร์ไพรส์", "ว้าว"],
        "vi": ["ngạc nhiên", "bất ngờ", "wow"],
        "id": ["terkejut", "kejutan", "wow"],
        "af": ["verbaas", "verrassing", "wow"],
        "fi": ["yllättynyt", "yllätys", "wow"],
        "sv": ["förvånad", "överraskning", "wow"],
        "no": ["overrasket", "overraskelse", "wow"],
        "da": ["overrasket", "overraskelse", "wow"],
        "ro": ["surprins", "surpriză", "wow"],
        "hu": ["meglepetés", "meglepett", "hú"],
        "bg": ["изненадан", "изненада", "уау"],
        "sr": ["iznenađen", "iznenađenje", "vau"],
        "hr": ["iznenađen", "iznenađenje", "vau"],
        "sk": ["prekvapený", "prekvapenie", "wow"],
        "lt": ["nustebęs", "nustebimas", "o"],
        "lv": ["pārsteigts", "pārsteigums", "vau"],
        "sl": ["presenečen", "presenečenje", "vau"],
        "et": ["üllatunud", "üllatus", "vau"],
        "eo": ["surprizita", "surprizo", "vau"],
        "la": ["miratus", "miraculum", "vau"],
    },
}


GREETINGS: Dict[str, str] = {
    "en": "Hello!", "es": "¡Hola!", "pt": "Olá!", "fr": "Bonjour !",
    "de": "Hallo!", "it": "Ciao!", "nl": "Hallo!", "el": "Γεια σας!",
    "ru": "Здравствуйте!", "uk": "Привіт!", "pl": "Cześć!", "cs": "Ahoj!",
    "sk": "Ahoj!", "ro": "Salut!", "hu": "Szia!", "bg": "Здравейте!",
    "sr": "Здраво!", "hr": "Bok!", "sl": "Živjo!", "lt": "Labas!",
    "lv": "Sveiki!", "et": "Tere!", "fi": "Hei!", "sv": "Hej!",
    "no": "Hei!", "da": "Hej!", "is": "Halló!", "ga": "Dia duit!",
    "cy": "Helo!", "eu": "Kaixo!", "ca": "Hola!", "gl": "Ola!",
    "mt": "Bonġu!", "lb": "Moien!", "tr": "Merhaba!", "ar": "مرحبا!",
    "he": "שלום!", "fa": "سلام!", "ur": "ہیلو!", "hi": "नमस्ते!",
    "bn": "হ্যালো!", "ta": "வணக்கம்!", "te": "హలో!", "mr": "नमस्कार!",
    "gu": "નમસ્તે!", "pa": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ!", "th": "สวัสดี!", "vi": "Xin chào!",
    "id": "Halo!", "ms": "Helo!", "tl": "Kumusta!", "ja": "こんにちは!",
    "ko": "안녕하세요!", "zh": "你好!", "yue": "你好!",
    "mn": "Сайн байна уу!", "sw": "Habari!", "yo": "Bawo!",
    "ig": "Ndewo!", "zu": "Sawubona!", "af": "Hallo!",
    "eo": "Saluton!", "la": "Salve!",
}


LANG_NAMES: Dict[str, str] = {
    "en": "English", "es": "Spanish", "pt": "Portuguese", "fr": "French",
    "de": "German", "it": "Italian", "nl": "Dutch", "el": "Greek",
    "ru": "Russian", "uk": "Ukrainian", "be": "Belarusian", "pl": "Polish",
    "cs": "Czech", "sk": "Slovak", "ro": "Romanian", "hu": "Hungarian",
    "bg": "Bulgarian", "sr": "Serbian", "hr": "Croatian", "bs": "Bosnian",
    "sl": "Slovenian", "mk": "Macedonian", "lt": "Lithuanian", "lv": "Latvian",
    "et": "Estonian", "fi": "Finnish", "sv": "Swedish", "no": "Norwegian",
    "da": "Danish", "is": "Icelandic", "ga": "Irish", "cy": "Welsh",
    "eu": "Basque", "ca": "Catalan", "gl": "Galician", "mt": "Maltese",
    "lb": "Luxembourgish", "tr": "Turkish", "az": "Azerbaijani",
    "kk": "Kazakh", "uz": "Uzbek", "ky": "Kyrgyz", "tg": "Tajik",
    "tk": "Turkmen", "ar": "Arabic", "he": "Hebrew", "fa": "Persian",
    "ur": "Urdu", "ps": "Pashto", "ku": "Kurdish", "sd": "Sindhi",
    "yi": "Yiddish", "am": "Amharic", "ti": "Tigrinya", "ha": "Hausa",
    "so": "Somali", "sw": "Swahili", "yo": "Yoruba", "ig": "Igbo",
    "zu": "Zulu", "xh": "Xhosa", "af": "Afrikaans", "st": "Sesotho",
    "tn": "Tswana", "ss": "Swati", "ve": "Venda", "ts": "Tsonga",
    "sn": "Shona", "rw": "Kinyarwanda", "rn": "Kirundi", "mg": "Malagasy",
    "ny": "Chichewa", "ak": "Twi", "tw": "Twi", "ee": "Ewe",
    "ln": "Lingala", "kg": "Kongo", "lu": "Luba-Katanga",
    "hi": "Hindi", "bn": "Bengali", "ta": "Tamil", "te": "Telugu",
    "mr": "Marathi", "gu": "Gujarati", "pa": "Punjabi", "kn": "Kannada",
    "ml": "Malayalam", "or": "Oriya", "as": "Assamese", "si": "Sinhala",
    "ne": "Nepali", "mai": "Maithili", "sa": "Sanskrit", "ks": "Kashmiri",
    "th": "Thai", "lo": "Lao", "km": "Khmer", "my": "Burmese", "bo": "Tibetan",
    "ka": "Georgian", "hy": "Armenian", "mn": "Mongolian",
    "chr": "Cherokee", "haw": "Hawaiian", "mi": "Maori", "sm": "Samoan",
    "to": "Tongan", "fj": "Fijian", "ty": "Tahitian",
    "vi": "Vietnamese", "id": "Indonesian", "ms": "Malay", "tl": "Tagalog",
    "jv": "Javanese", "su": "Sundanese", "ceb": "Cebuano", "ilo": "Ilocano",
    "ja": "Japanese", "ko": "Korean", "zh": "Chinese", "yue": "Cantonese",
    "eo": "Esperanto", "ia": "Interlingua", "ie": "Interlingue", "vo": "Volapük",
    "la": "Latin", "ang": "Old English", "non": "Old Norse", "grc": "Ancient Greek",
    "syc": "Classical Syriac", "arc": "Aramaic", "phn": "Phoenician",
    "uga": "Ugaritic", "hit": "Hittite", "xcl": "Classical Armenian",
    "pal": "Middle Persian", "peo": "Old Persian", "ave": "Avestan",
    "san": "Sanskrit", "pra": "Prakrit", "pli": "Pali", "skt": "Sanskrit",
    "myn": "Mayan", "nah": "Nahuatl", "quc": "K'iche'", "que": "Quechua",
    "aym": "Aymara", "arn": "Mapuche", "gn": "Guarani", "tet": "Tetum",
    "sgn": "Sign language", "ase": "ASL", "fsl": "FSL", "bfi": "BSL",
    "und": "Undetermined", "mul": "Multilingual",
}


# ---------------------------------------------------------------------------
# Expanded vocabulary for the most widely used languages.
#
# The base lexicon above is intentionally compact. These additions deepen
# the languages people are most likely to type in (English and Greek first).
# Entries are merged by ``_extend`` below, duplicates are ignored.
# ---------------------------------------------------------------------------
_EXTRA: Dict[str, Dict[str, List[str]]] = {
    "joy": {
        "en": ["pleased", "cheerful", "grateful", "thankful", "hopeful", "hope",
               "enjoy", "enjoyed", "enjoying", "fun", "lovely", "brilliant",
               "superb", "terrific", "cool", "nice", "sweet", "hooray", "haha",
               "hahaha", "relieved", "relief", "cheers", "celebration",
               "birthday", "good news", "adore", "adored", "delight",
               "optimistic", "overjoyed", "ecstatic", "elated", "stoked",
               "grateful", "appreciate", "appreciated", "got the job",
               "passed the exam", "cant wait", "love it", "love you", "proud of"],
        "el": ["χαρούμενος", "χαρούμενη", "χαρούμενο", "χαίρομαι", "ευτυχισμένος",
               "ευτυχισμένη", "ευτυχία", "ευτυχής", "υπέροχος", "υπέροχη",
               "υπέροχο", "φανταστικός", "φανταστική", "φανταστικό",
               "καταπληκτικός", "καταπληκτικό", "τέλειος", "τέλειο", "μπράβο",
               "συγχαρητήρια", "ευχαριστώ", "ευχαριστούμε", "αγαπάω", "αγαπώ",
               "σ' αγαπώ", "σε αγαπώ", "ερωτευμένος", "ερωτευμένη", "περήφανος",
               "περήφανη", "ενθουσιασμένος", "ενθουσιασμένη", "ενθουσιασμός",
               "γέλιο", "γελάω", "χαμόγελο", "γιορτάζω", "γιορτή", "κέρδισα",
               "πέτυχα", "προαγωγή", "προήχθην", "προσλήφθηκα", "απόλαυση",
               "ωραίος", "ωραία", "ωραίο", "καλά νέα", "ευγνώμων",
               "ανακουφισμένος", "ανακουφισμένη", "δεν βλέπω την ώρα",
               "μια χαρά", "τέλεια", "άριστα", "εξαιρετικός", "εξαιρετικά νέα"],
        "es": ["contento", "contenta", "emocionado", "emocionada", "orgulloso",
               "orgullosa", "felicidades", "enhorabuena", "ascenso", "encantado",
               "encantada", "me encanta", "bien", "buenas noticias", "gané"],
        "fr": ["content", "contente", "ravi", "ravie", "enchanté", "fier",
               "fière", "félicitations", "bravo", "super", "excellent",
               "bonne nouvelle", "j'adore", "magnifique"],
        "de": ["froh", "zufrieden", "stolz", "begeistert", "glückwunsch",
               "herzlichen glückwunsch", "prima", "klasse", "großartig",
               "gute nachrichten", "ich liebe dich"],
        "it": ["contento", "contenta", "orgoglioso", "orgogliosa", "emozionato",
               "congratulazioni", "bravo", "ottimo", "meraviglioso",
               "buone notizie", "ti amo", "bellissimo"],
        "pt": ["contente", "orgulhoso", "orgulhosa", "emocionado", "parabéns",
               "maravilhoso", "boas notícias", "te amo", "adoro"],
        "ru": ["рад", "рада", "радостный", "счастливый", "счастливая", "доволен",
               "довольна", "горжусь", "поздравляю", "прекрасно", "замечательно",
               "обожаю", "ура", "восхитительно"],
    },
    "sadness": {
        "en": ["miserable", "gloomy", "devastated", "disappointed", "disappointing",
               "disappointment", "hopeless", "heartache", "mourn", "mourning",
               "loneliness", "empty", "numb", "hurting", "tearful", "sobbing",
               "cried", "weeping", "passed away", "died", "death", "funeral",
               "breakup", "broke up", "left me", "miss you", "missed you",
               "homesick", "failed", "failure", "rejected", "ignored",
               "worst day", "lost him", "lost her", "want you back",
               "wish you were here", "feel down", "feeling down", "upset",
               "ex back", "ex"],
        "el": ["λυπημένος", "λυπημένη", "λυπημένο", "λύπη", "στεναχωρημένος",
               "στεναχωρημένη", "στεναχώρια", "θλιμμένος", "θλιμμένη", "θλίψη",
               "κλαίω", "κλάμα", "κλαίει", "δάκρυα", "μοναξιά", "μοναχικός",
               "απογοητευμένος", "απογοητευμένη", "απογοήτευση",
               "καταθλιπτικός", "πληγωμένος", "πληγωμένη", "πόνος", "πονάω",
               "ραγισμένη καρδιά", "μου λείπεις", "μου λείπουν", "χωρισμός",
               "χωρίσαμε", "με άφησε", "με παράτησε", "πέθανε", "θάνατος",
               "κηδεία", "πένθος", "συντετριμμένος", "συντετριμμένη",
               "απελπισία", "απελπισμένος", "απελπισμένη", "άδειος", "άδεια",
               "κενό", "νοσταλγία", "αποτυχία", "ήττα", "πρώην", "χάλια μου",
               "χειρότερη μέρα", "δεν αντέχω", "δεν είμαι καλά", "θέλω να κλάψω"],
        "es": ["deprimido", "deprimida", "llorando", "decepcionado", "decepcionada",
               "desolado", "desolada", "lo siento", "te echo de menos",
               "pérdida", "murió", "duelo", "mi ex", "peor día"],
        "fr": ["déprimé", "déprimée", "chagrin", "déçu", "déçue", "désolé",
               "malheureux", "triste", "tu me manques", "mon ex", "pire journée",
               "deuil", "il est mort", "elle est morte"],
        "de": ["deprimiert", "enttäuscht", "betrübt", "unglücklich", "trauer",
               "ich vermisse dich", "mein ex", "schlimmster tag", "gestorben"],
        "it": ["depresso", "depressa", "deluso", "delusa", "infelice", "piango",
               "il mio ex", "peggior giorno", "è morto", "è morta", "lutto"],
        "pt": ["deprimido", "deprimida", "decepcionado", "decepcionada", "infeliz",
               "meu ex", "pior dia", "morreu", "luto", "sinto falta"],
        "ru": ["печально", "грустно", "тоскую", "расстроен", "расстроена",
               "разочарован", "несчастный", "умер", "потеря", "депрессия",
               "мой бывший", "моя бывшая", "хочу вернуть"],
    },
    "anger": {
        "en": ["livid", "outraged", "outrage", "enraged", "irate", "hatred",
               "resent", "resentment", "fed up", "sick and tired", "annoying",
               "annoys", "infuriating", "unacceptable", "ridiculous", "bullshit",
               "fuck", "fucking", "shit", "asshole", "bastard", "jerk", "moron",
               "scam", "betrayed", "betrayal", "lied to", "liar", "how dare",
               "cant stand", "had enough", "pissed off", "so mad", "hate you"],
        "el": ["θυμωμένος", "θυμωμένη", "θυμωμένο", "θυμώνω", "θυμός", "οργή",
               "οργισμένος", "οργισμένη", "εξοργισμένος", "εξοργισμένη",
               "νευρίασα", "νευριασμένος", "νευριασμένη", "νεύρα",
               "εκνευρισμένος", "εκνευρισμένη", "εκνευρίζομαι", "μισώ", "μίσος",
               "ηλίθιος", "ηλίθια", "βλάκας", "μαλάκας", "γαμώτο", "γαμημένος",
               "παλιάνθρωπος", "αγανάκτηση", "αγανακτισμένος", "ενοχλημένος",
               "εκνευριστικός", "απαράδεκτος", "απαράδεκτο", "προδοσία",
               "ψεύτης", "δεν αντέχω άλλο", "έχω φτάσει στο απροχώρητο",
               "με έχει τρελάνει", "με έχει εκνευρίσει", "βαρέθηκα"],
        "es": ["molesto", "molesta", "furioso", "furiosa", "cabreado", "cabreada",
               "harto", "harta", "me enfurece", "maldito", "mentiroso",
               "inaceptable", "indignado", "indignada"],
        "fr": ["furieux", "furieuse", "énervé", "énervée", "agacé", "marre",
               "j'en ai marre", "inacceptable", "menteur", "con", "putain"],
        "de": ["sauer", "verärgert", "genervt", "empört", "satt", "scheiße",
               "lügner", "inakzeptabel", "ich hasse"],
        "it": ["furioso", "furiosa", "arrabbiata", "incazzato", "incazzata",
               "stufo", "stufa", "inaccettabile", "bugiardo", "odio"],
        "pt": ["furioso", "furiosa", "chateado", "chateada", "farto", "farta",
               "inaceitável", "mentiroso", "puto"],
        "ru": ["злюсь", "бесит", "взбешён", "ненавижу", "раздражает", "достал",
               "возмущён", "возмутительно", "сволочь", "дурак"],
    },
    "fear": {
        "en": ["fearful", "petrified", "panicking", "dread", "dreading", "uneasy",
               "threatened", "terror", "horror", "nightmare", "trembling",
               "what if", "freaking out", "freaked out", "scary", "creepy",
               "cant sleep", "so worried", "afraid of"],
        "el": ["φοβισμένος", "φοβισμένη", "φοβισμένο", "φόβος", "φοβάμαι",
               "τρομαγμένος", "τρομαγμένη", "τρόμος", "τρομάζω", "άγχος",
               "αγχωμένος", "αγχωμένη", "αγχώνομαι", "ανήσυχος", "ανήσυχη",
               "ανησυχία", "ανησυχώ", "πανικός", "πανικόβλητος", "πανικόβλητη",
               "επικίνδυνος", "απειλή", "εφιάλτης", "νευρικός", "νευρική",
               "αγωνία", "αβεβαιότητα", "τρέμω", "με τρομάζει", "με φοβίζει",
               "δεν κοιμάμαι", "κρύος ιδρώτας", "τι θα γίνει"],
        "es": ["pánico", "ansiedad", "temblando", "pesadilla", "me da miedo",
               "tengo miedo", "terror", "inquieto", "inquieta"],
        "fr": ["paniqué", "paniquée", "angoisse", "anxiété", "cauchemar",
               "j'ai peur", "effrayant", "terreur", "inquiétant"],
        "de": ["panik", "ich habe angst", "albtraum", "unheimlich", "furcht",
               "beunruhigt", "nervös"],
        "it": ["panico", "ansia", "incubo", "ho paura", "spaventoso", "terrore",
               "agitato", "agitata"],
        "pt": ["pânico", "ansiedade", "pesadelo", "tenho medo", "assustador",
               "terror", "nervoso", "nervosa"],
        "ru": ["паника", "тревога", "кошмар", "страшно", "ужас", "боюсь",
               "переживаю", "волнуюсь", "нервничаю"],
    },
    "disgust": {
        "en": ["vile", "sickening", "nauseating", "nauseous", "filthy", "rotten",
               "rancid", "stink", "stinks", "smelly", "puke", "vomit",
               "appalling", "appalled", "horrid", "worst", "gag", "skeevy",
               "makes me sick", "so gross"],
        "el": ["αηδία", "αηδιαστικός", "αηδιαστική", "αηδιαστικό", "αηδιασμένη",
               "σιχαίνομαι", "σιχαμερός", "σιχαμερή", "σιχαμερό", "βρώμικος",
               "βρωμερός", "βρωμερή", "αποκρουστική", "αποκρουστικό", "ναυτία",
               "εμετός", "αποτρόπαιος", "φρικτός", "φρικτή", "φρικτό",
               "απαίσια", "απαίσιο", "απαίσιος", "σιχαίνομαι", "μου προκαλεί αηδία",
               "μου ανακατεύεται το στομάχι", "σιχαμάρα"],
        "es": ["repugnancia", "asquerosa", "asqueroso", "me da asco", "vomitar",
               "sucio", "sucia", "apestoso"],
        "fr": ["dégueulasse", "écœurant", "écœurée", "beurk", "immonde",
               "ça me dégoûte", "sale", "puant"],
        "de": ["igitt", "eklig", "abstoßend", "schmutzig", "übel", "kotzen",
               "widerwärtig", "stinkt"],
        "it": ["schifo", "schifoso", "disgustoso", "ripugnante", "che schifo",
               "sporco", "puzzolente", "nauseante"],
        "pt": ["nojento", "nojenta", "asqueroso", "que nojo", "sujo", "fedido",
               "repulsivo"],
        "ru": ["тошнит", "мерзко", "фу", "противно", "гадость", "омерзительно",
               "грязный", "воняет"],
    },
    "surprise": {
        "en": ["stunned", "astonished", "astonishing", "amazed", "speechless",
               "unexpected", "unexpectedly", "suddenly", "whoa", "mind blown",
               "didnt expect", "out of nowhere", "shocking"],
        "el": ["έκπληξη", "έκπληκτος", "έκπληκτη", "ξαφνικά", "ξαφνιάστηκα",
               "ξαφνιασμένος", "ξαφνιασμένη", "απίστευτο", "δεν το πιστεύω",
               "ουάου", "αναπάντεχο", "αναπάντεχη", "σοκαρισμένος",
               "σοκαρισμένη", "σοκ", "άφωνος", "άφωνη", "απρόσμενο",
               "δεν περίμενα", "τι έγινε τώρα", "μα τι λες"],
        "es": ["asombrado", "asombrada", "impactado", "de repente", "inesperado",
               "no me lo esperaba", "no puedo creer", "sin palabras", "vaya"],
        "fr": ["étonné", "étonnée", "stupéfait", "soudain", "inattendu",
               "je n'en reviens pas", "sans voix", "waouh"],
        "de": ["erstaunt", "verblüfft", "plötzlich", "unerwartet",
               "ich kann es nicht glauben", "sprachlos"],
        "it": ["stupito", "stupita", "sbalordito", "all'improvviso", "inaspettato",
               "non ci credo", "senza parole"],
        "pt": ["espantado", "chocado", "de repente", "inesperado",
               "não acredito", "sem palavras"],
        "ru": ["шокирован", "потрясён", "внезапно", "неожиданно",
               "не могу поверить", "офигеть", "вау", "не ожидал"],
    },
}

_EXTRA["joy"]["en"] += ["happier", "happiest", "happily", "could not be happier",
                        "couldnt be happier", "cant be happier", "over the moon",
                        "on top of the world", "best day", "so happy"]
_EXTRA["joy"]["it"] += ["felicissimo", "felicissima", "felicissimi"]
_EXTRA["joy"]["el"] += ["πανευτυχής", "πανευτυχές", "πανευτυχείς", "ενθουσιάστηκα",
                        "τρελή χαρά", "πετάω από τη χαρά"]
_EXTRA["joy"]["ko"] = ["행복", "기쁘", "기뻐", "좋아", "고마", "사랑", "최고", "즐거"]
_EXTRA["sadness"]["ko"] = ["슬프", "슬퍼", "슬픔", "외롭", "외로", "눈물", "그리", "우울", "이별"]
_EXTRA["anger"]["ko"] = ["화나", "화가", "짜증", "분노", "미워", "싫어", "열받"]
_EXTRA["fear"]["ko"] = ["무서", "두려", "불안", "걱정"]
_EXTRA["disgust"]["ko"] = ["역겨", "혐오", "끔찍", "징그"]
_EXTRA["surprise"]["ko"] = ["놀라", "놀람", "대박", "헐"]
_EXTRA["anger"]["en"] += ["outrageous", "disgraceful", "pathetic", "sick of it", "demand a refund"]
_EXTRA["anger"]["el"] += ["εκνευρίζει", "εκνευρίζεις", "εκνευρίζουν", "εξόργισες",
                          "εξοργίζει", "ενοχλεί", "με ενοχλεί", "δεν το αντέχω",
                          "έξαλλος", "έξαλλη", "έξαλλο"]
_EXTRA["sadness"]["es"] += ["echo de menos", "lloro", "lloras", "lloré", "extraño a",
                            "me siento solo", "me siento sola"]
_EXTRA["sadness"]["el"] += ["στεναχωριέμαι", "στεναχωριέται", "στενοχωριέμαι",
                            "στενοχωρημένος", "στενοχωρημένη", "στενοχώρια",
                            "έκλαψα", "κλαίω", "κλαίγομαι"]
_EXTRA["fear"]["en"] += ["spooked", "frightening", "worried sick", "my anxiety"]
_EXTRA["disgust"]["en"] += ["spat it out", "mold", "mould", "maggots"]

_EXTRA["anger"]["en"] += ["driving me crazy", "drives me crazy", "drive me crazy",
                          "driving me nuts", "disgrace", "done with this",
                          "get out of my sight", "infuriated"]
_EXTRA["joy"]["en"] += ["finally got", "new home", "new house", "dancing"]
_EXTRA["anger"]["el"] += ["εκνευρίσει", "εκνευρίστηκα", "με έχει εκνευρίσει",
                          "δεν τον αντέχω", "δεν την αντέχω", "τρελαίνομαι", "με προσβάλλεις"]
_EXTRA["sadness"]["es"] += ["destrozado", "destrozada", "me duele", "partido el corazón"]
_EXTRA["joy"]["de"] += ["freue mich", "freut mich", "riesig", "beste nachricht", "freue", "begeistert"]
_EXTRA["anger"]["de"] += ["sauer", "frechheit", "unverschämt", "kotzt mich an"]
_EXTRA["anger"]["tr"] = ["sinirli", "kızgın", "öfkeli", "nefret", "kabul edilemez", "bıktım", "sinir"]
_EXTRA["joy"]["tr"] = ["mutlu", "sevin", "harika", "teşekkür", "güzel", "süper"]
_EXTRA["sadness"]["tr"] = ["üzgün", "üzül", "hüzün", "ağla", "yalnız", "özle"]
_EXTRA["fear"]["tr"] = ["korku", "endişe", "kork", "panik", "tedirgin"]
_EXTRA["anger"]["ja"] = ["腹が立つ", "腹立", "許せない", "ムカつく", "むかつく", "イライラ", "いらいら"]
_EXTRA["fear"]["ja"] = ["怖い", "こわい", "不安", "恐ろしい", "心配", "怯え"]
_EXTRA["sadness"]["ja"] = ["悲しい", "寂しい", "涙", "辛い", "つらい", "切ない"]
_EXTRA["joy"]["ja"] = ["嬉しい", "うれしい", "楽しい", "幸せ", "最高", "ありがとう", "やった"]
_EXTRA["fear"]["zh"] = ["害怕", "担心", "恐惧", "焦虑", "紧张"]


def _extend() -> None:
    for emotion, by_lang in _EXTRA.items():
        for lang, words in by_lang.items():
            bucket = LEXICON[emotion].setdefault(lang, [])
            known = set(bucket)
            for w in words:
                if w not in known:
                    bucket.append(w)
                    known.add(w)


_extend()


# More negation / intensifier words (merged into the tables above).
NEGATIONS.update({
    "el": NEGATIONS["el"] | {"δε", "ούτε", "χωρίς", "ποτέ"},
    "ru": {"не", "нет", "никогда", "ни", "без"},
    "nl": {"niet", "geen", "nooit", "nergens"},
    "sv": {"inte", "aldrig", "ingen", "ej"},
    "no": {"ikke", "aldri", "ingen"},
    "da": {"ikke", "aldrig", "ingen"},
    "pl": {"nie", "nigdy", "bez"},
    "ro": {"nu", "niciodată", "fără"},
    "id": {"tidak", "bukan", "tak", "belum", "jangan"},
})
INTENSIFIERS.update({
    "en": INTENSIFIERS["en"] | {"deeply", "truly", "insanely", "so so", "fucking",
                                "damn", "well", "bloody", "hella"},
    "el": INTENSIFIERS["el"] | {"τόσο", "υπερβολικά", "εντελώς", "τελείως", "ολοκληρωτικά",
                                "ανεπανάληπτα", "σούπερ", "πολύ πολύ"},
    "ru": {"очень", "крайне", "совсем", "ужасно", "невероятно", "так"},
    "nl": {"zeer", "heel", "erg", "ontzettend"},
    "sv": {"mycket", "väldigt", "jättebra", "otroligt"},
    "no": {"veldig", "utrolig", "svært"},
    "da": {"meget", "virkelig", "utrolig"},
    "pl": {"bardzo", "niezwykle", "strasznie"},
    "id": {"sangat", "banget", "sekali", "amat"},
})


# ---------------------------------------------------------------------------
# Language identification helpers
# ---------------------------------------------------------------------------

# Very common function words per Latin-script language. Matched against
# lower-cased tokens exactly as written (accents included). Combined with
# lexicon hits and diacritic hints in ``EmotionDetection.language``.
STOPWORDS: Dict[str, List[str]] = {
    "en": ["the", "and", "is", "are", "was", "were", "i", "you", "my", "it",
           "this", "that", "to", "of", "in", "with", "for", "have", "has",
           "not", "am", "so", "just", "very", "but", "me", "we", "be", "im",
           "dont", "cant", "ive", "today", "back", "want", "what", "when",
           "your", "they", "he", "she", "do", "did", "would", "about"],
    "es": ["el", "los", "las", "de", "que", "y", "en", "un", "una", "es",
           "estoy", "mi", "mis", "tu", "te", "muy", "pero", "por", "con",
           "para", "se", "lo", "está", "esta", "soy", "eres", "hoy",
           "contigo", "yo", "tengo", "como", "más", "mas", "qué", "ayer"],
    "pt": ["os", "as", "de", "que", "em", "um", "uma", "é", "estou", "meu",
           "minha", "muito", "mas", "com", "para", "não", "nao", "eu", "você",
           "voce", "hoje", "sou", "está", "tenho", "isso", "ela", "ele",
           "também", "tambem", "são"],
    "fr": ["le", "les", "des", "du", "et", "est", "un", "une", "je", "tu",
           "il", "nous", "vous", "suis", "très", "tres", "pas", "pour", "avec",
           "mais", "ce", "cette", "mon", "ma", "mes", "jai", "cest", "qui",
           "que", "aujourd", "dans", "elle", "ça"],
    "de": ["der", "die", "das", "und", "ist", "ich", "du", "nicht", "ein",
           "eine", "mit", "für", "zu", "auf", "sehr", "bin", "mein", "meine",
           "aber", "wie", "heute", "es", "mir", "mich", "dich", "wir", "sie",
           "habe", "auch", "noch"],
    "it": ["il", "lo", "gli", "di", "che", "è", "un", "una", "sono", "io",
           "non", "molto", "per", "con", "ma", "mio", "mia", "oggi", "questo",
           "ho", "sei", "mi", "ti", "anche", "della", "nel", "cosa"],
    "nl": ["de", "het", "een", "en", "is", "ik", "je", "jij", "niet", "van",
           "dat", "die", "met", "voor", "zeer", "heel", "maar", "mijn", "ben",
           "vandaag", "op", "te", "zijn", "ook", "wat", "hoe"],
    "sv": ["och", "att", "det", "är", "jag", "du", "inte", "ett", "som",
           "på", "för", "med", "mycket", "men", "min", "mitt", "idag", "har",
           "vi", "så", "den", "kan", "mig"],
    "no": ["og", "det", "er", "jeg", "du", "ikke", "et", "som", "på", "for",
           "med", "veldig", "men", "min", "mitt", "dag", "har", "vi", "så",
           "meg", "deg", "jeg"],
    "da": ["og", "at", "det", "er", "jeg", "du", "ikke", "som", "på", "for",
           "med", "meget", "men", "min", "mit", "har", "vi", "så", "mig",
           "dig", "bare"],
    "fi": ["ja", "on", "ei", "että", "minä", "olen", "sinä", "se", "mutta",
           "hyvin", "tänään", "kanssa", "niin", "tämä", "mä", "oli", "mulla",
           "kun", "oikein"],
    "pl": ["w", "nie", "to", "jest", "się", "że", "na", "jestem", "bardzo",
           "ale", "mój", "moja", "dziś", "z", "mam", "ja", "ty", "jak", "co",
           "dzisiaj", "tak"],
    "cs": ["je", "se", "na", "to", "že", "jsem", "jsi", "ne", "ale", "velmi",
           "dnes", "mám", "já", "ty", "můj", "moje", "jak", "co", "tak"],
    "tr": ["ve", "bir", "bu", "ben", "sen", "çok", "ama", "değil", "için",
           "ile", "bugün", "ne", "de", "da", "benim", "mi", "çünkü", "gibi"],
    "id": ["dan", "yang", "di", "itu", "ini", "saya", "aku", "kamu", "tidak",
           "sangat", "tapi", "dengan", "untuk", "hari", "adalah", "sudah",
           "banget", "nggak", "gak"],
    "ro": ["și", "este", "sunt", "eu", "tu", "nu", "un", "foarte", "dar",
           "cu", "pentru", "azi", "astăzi", "mă", "să", "am", "ce", "mi"],
    "hu": ["és", "az", "egy", "nem", "vagyok", "én", "te", "nagyon", "de",
           "ma", "hogy", "van", "ez", "nekem", "mi", "vagy"],
    "ca": ["el", "de", "que", "és", "un", "una", "estic", "molt", "però",
           "amb", "per", "avui", "jo", "no", "em", "estic", "tinc"],
    "hr": ["je", "se", "da", "u", "na", "sam", "ja", "ti", "nije", "vrlo",
           "ali", "danas", "sa", "za", "mi", "nisam", "što"],
    "af": ["die", "en", "is", "ek", "jy", "nie", "baie", "maar", "vandag",
           "my", "het", "dit", "van"],
    "tl": ["ang", "ng", "sa", "ako", "ikaw", "hindi", "ay", "ko", "mo", "na",
           "sobrang", "pero", "ngayon", "po", "ka", "siya"],
    "vi": ["tôi", "không", "và", "là", "rất", "của", "hôm", "nay", "bạn",
           "anh", "em", "một", "có", "này"],
    "sw": ["na", "ni", "ya", "wa", "kwa", "sana", "mimi", "wewe", "leo",
           "siku", "si", "sijui"],
}

# A character that is (nearly) diagnostic for one or a few Latin-script
# languages. Each occurrence nudges those languages up a little.
DIACRITIC_HINTS: Dict[str, List[str]] = {
    "ñ": ["es"], "¿": ["es"], "¡": ["es"],
    "ã": ["pt"], "õ": ["pt"],
    "ß": ["de"], "ä": ["de", "sv", "fi"], "ö": ["de", "sv", "fi", "tr", "hu"],
    "ü": ["de", "tr", "hu"], "å": ["sv", "no", "da"], "ø": ["no", "da"],
    "æ": ["no", "da"], "œ": ["fr"], "è": ["fr", "it"], "ê": ["fr", "pt"],
    "ë": ["fr", "nl"], "à": ["fr", "it", "pt", "ca"], "â": ["fr", "pt", "ro"],
    "ù": ["fr", "it"], "î": ["fr", "ro"], "ô": ["fr", "pt", "vi"],
    "ò": ["it", "ca"], "ì": ["it"], "ç": ["fr", "pt", "ca", "tr"],
    "ő": ["hu"], "ű": ["hu"], "ł": ["pl"], "ą": ["pl"], "ę": ["pl"],
    "ś": ["pl"], "ć": ["pl", "hr"], "ź": ["pl"], "ż": ["pl"], "ń": ["pl"],
    "ř": ["cs"], "ě": ["cs"], "ů": ["cs"], "ğ": ["tr"], "ş": ["tr", "ro"],
    "ı": ["tr"], "đ": ["hr", "vi"], "ă": ["ro", "vi"], "ș": ["ro"], "ț": ["ro"],
    "ơ": ["vi"], "ư": ["vi"], "ạ": ["vi"], "ế": ["vi"], "ệ": ["vi"],
}

# Languages written without spaces between words: exact token matching is
# impossible, so the analyzer falls back to substring matching (and cannot
# do negation / intensifier handling for them).
NO_SPACE_LANGS = {"ja", "zh", "yue", "th"}

# Heavily inflected languages. A lexicon word of 6+ letters also matches a
# token that shares its stem (the word minus its last two letters), so e.g.
# "λυπημένος" also catches "λυπημένη" and "λυπημένοι".
INFLECTED_LANGS = {"el", "ru", "uk", "bg", "sr", "hr", "sk", "cs", "pl", "sl",
                   "lt", "lv"}

# Agglutinative languages attach suffixes to the stem ("mutlu" -> "mutluyum",
# "행복" -> "행복해요"), so a token that merely *starts with* a lexicon word
# matches. Value = minimum stem length in characters.
AGGLUTINATIVE_LANGS: Dict[str, int] = {"tr": 4, "fi": 4, "hu": 4, "et": 4, "ko": 2}
